# Generated by Django 2.2.5 on 2019-10-21 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Key (use for front)')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Partner Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo')),
                ('link', models.URLField(blank=True, max_length=1024, null=True, verbose_name='Url to partner')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('partner_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artwork.PartnerType', verbose_name='Type')),
            ],
        ),
    ]
